# Generated by Django 5.1.1 on 2024-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
