# Generated by Django 5.2 on 2025-04-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_seat_available_event_available_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_published',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=100),
        ),
    ]
