# Generated by Django 5.1.1 on 2025-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_is_cancelled_remove_event_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='features',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
