# Generated by Django 5.1.1 on 2025-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_features_remove_event_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
