# Generated by Django 5.1.1 on 2025-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_actual_price_alter_event_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
