# Generated by Django 5.1.1 on 2025-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
