# Generated by Django 5.1.1 on 2025-06-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
