version: "3.8"

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: event_redis
    networks:
      - event-network

  db:
    image: postgres:16
    container_name: event_database
    restart: always
    expose:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
      # - POSTGRES_USER=postgres
      # - POSTGRES_DB=gnf
    volumes:
      - event-db-data:/var/lib/postgresql/data
    networks:
      - event-network

  api:
    container_name: event_api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py create_admin
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis
    networks:
      - event-network

  celery:
    container_name: event_celery
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - api
    networks:
      - event-network

  celery-beat:
    container_name: event_celery_beat
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: celery -A core beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - api
      - celery
    networks:
      - event-network

volumes:
  event-db-data:

networks:
  event-network:
    driver: bridge
