name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            echo "👉 Pulling latest code"
            cd /var/www/Travelomo
            git pull origin main

            echo "🧹 Stopping and cleaning old containers"
            docker compose down

            echo "🧼 Pruning unused Docker data"
            docker system prune -af

            echo "🚀 Rebuilding and starting containers"
            docker compose up --build -d

            echo "✅ Deployment complete!"
